### ISSUE TITLE
[2주차][은지]

### ISSUE THREAD

**Issue by eunji0714** [FE-STUDY-2024/JS-Study#12]
### 퀴즈
1. ?를 채우고 그 이유를 간단하게 서술하시오
```
let x = 10;

function foo() {
	let x = 20;
	bar();
}

function bar() {
	console.log(x);
}

foo(); // ?
x = 30;
bar(); // ?
```

2. 프로퍼티의 [[configurable]] 어트리뷰트가 false로 설정되었을 때 어떤 작업이 불가능한가요?

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
정답 설명
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by hayamaster** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
<br/>
1. 10, 30 
<br/>
2. 프로퍼티를 삭제할 수 없게 됩니당.
</div>
</details>

**Comment by maylh** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1. 10 30 (bar() 함수 내에서 x는 전역 스코프에서의 x를 참조하게 되므로 1은 10, 전역 스코프의 x가 30으로 재할당되었으므로 2는 30)
2. 값을 변경할 수 없다 
</div>
</details>

**Comment by nayoung3669** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1. 10, 30
2. 디스크립터 객체의 변경이 불가합니다.
</div>
</details>

**Comment by Minkyu0424** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1번답 10, 30
2번답 프로퍼티 값 추가 불가
</div>
</details>
