### ISSUE TITLE
[2주차][가현]

### ISSUE THREAD

**Issue by maylh** [FE-STUDY-2024/JS-Study#13]
### 퀴즈

Q1. 다음 중 옳지 않은 설명을 모두 고르시오.

1. 생성자 함수는 인스턴스를 생성하고 초기화하는 역할을 한다.
2.  객체 리터럴에 의한 객체 생성 방식은 동일한 프로퍼티를 갖는 객체를 여러 개 생성해야 하는 경우에 효율적인 방법이다.  
3. 생성자 함수 내부의 모든 처리가 끝나면 완성된 인스턴스가 바인딩된 this가 암묵적으로 반환된다. 
4. 모든 함수 객체는 생성자 함수로 호출할 수 있다.
5. 생성자 함수가 반환하는 값은 항상 생성된 인스턴스 자체이며, 다른 값을 반환하면 생성자 함수의 동작이 비정상적으로 이루어진다. 

<hr>

Q2. 아래 코드의 실행 결과는 ?
```
const func1 = function( ) { 
    console.log("hello");
 };
 
 const func2 = ( ) => {
     console.log("hello");
  };
 
 new func1();   // (1)
 new func2();   // (2) 
```

### 답

<details>
<summary>정답</summary>
<div markdown="1">   
Q1. 2, 4 <br>
2번 - 여러 개의 동일한 프로퍼티를 가진 객체를 생성하는 데는 생성자 함수가 더 유용하다. <br>
4번 - 모든 함수 객체는 호출할 수 있지만 모든 함수 객체를 생성자 함수로서 호출할 수 있는 것은 아니다.

Q2.
(1) hello
함수 표현식으로 정의된 함수는 constructor (생성자 함수로서 호출 가능)
(2) TypeError : func2 is not a constructor
화살표 함수로 정의된 함수는 non-constructor(객체를 생성자 함수로서 호출할 수 없음)
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by hayamaster** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
<br/>
1. 2, 4
<br/>
2. hello, undefined
</div>
</details>

**Comment by eunji0714** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1. 2번
<br />
2. hello, Type error
</div>
</details>

**Comment by nayoung3669** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1. (1, 3)
2. (1) - 빈 객체 {}, (2) - 에러:  익명함수라 constructor가 없음
</div>
</details>

**Comment by Minkyu0424** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
2번,  hello, 모르겠습니다
</div>
</details>
