### ISSUE TITLE
[2주차][나영]

### ISSUE THREAD

**Issue by nayoung3669** [FE-STUDY-2024/JS-Study#14]
### 퀴즈

1번. const person = {} 라는 빈 객체를 할당한 후,
  1) Object.defineProperty(‘age’, { value : 20 })
  2) person.age = “20”
  1번과 2번의 방법으로 프로퍼티를 동적으로 추가했을 때, writable, enumerable, configurable은 각각 무엇으로 초기화되나요? (boolean값 중)

2번. 함수가 ‘일급 객체’다. 라는건 무엇을 의미하나요?

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
정답 설명
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by hayamaster** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1. 
<br/>
  - false, false, false
<br/>
  - true, true, true
<br/>
2. 일반 객체와는 다른(추가적인) 내부 슬롯과 내부 메서드를 가진다. arguments, caller, length 등
</div>
</details>

**Comment by maylh** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1.  false false false / true true true 
2. 함수와 객체를 동일하게 사용할 수 있다 ......?
</div>
</details>

**Comment by eunji0714** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1.
<br />
(1) false, false, false
<br /> 
(2) true, true, true
<br />
2. 함수를 객체와 동일하게 사용할 수 있다
-> 함수의 매게변수에 전달하거나 반환값으로 사용할 수 있다
</div>
</details>

**Comment by Minkyu0424** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1번답 : ttf, fff
2번답 : 함수안의 매개변수로 이용가능, 배열, 객체안에 들어갈 수 있음, 또 어
</div>
</details>
